Unklare Erklärung individueller Choice Option Attribute
yakamara/redaxo_yform_docs pull request #133
Opened 2019-04-11 10:49 UTC by dtpop

Einzelne Attribute getrennt. Mit yform 3.1 getestet per php Notation. Gerne nochmal gegenchecken!

2019-04-11 11:31 UTC, AWqxKAWERbXo requested changes
Ich finde Äpfel und Birnen als Beispiel zu abstrakt/unkonkret. Ein klassischer Anwedungsfall wäre

* Elemente auf disabled setzen
* Class überschreiben
* Data-Attribute mitgeben (vielleicht ein Preis-Kalkulator wie in meinem Fall? Oder vergleichbare Eigenschaften?)

Ich würde es lieber sehen, wenn solche Beispiele in der Doku sind. Wärst du damit einverstanden?

Außerdem fehlt der Syntax für die Pipe-Schreibweise, dort hast du die PHP-Schreibweise notiert.

2019-04-11 11:52 UTC, tbaddade commented
oder wartet erst einmal bis das Issue hier https://github.com/yakamara/redaxo_yform/issues/717#issuecomment-482076350 bearbeitet wurde

2019-10-19 06:10 UTC, alexplusde commented
@dtpop würdest du mein Feedback schon mal mit einarbeiten? Da sich im anderen Issue nichts tut, würde ich deinen PR gerne übernehmen.

2019-12-14 10:04 UTC, alexplusde commented
@dtpop ping

2019-12-15 13:15 UTC, alexplusde commented
Die Branch ist inzwischen gelöscht, sodass ich keine Anpassungen daran noch vornehmen kann.

2019-12-15 13:15 UTC, closed without merging