Dateien als Anhang in der E-Mail mitsenden
yakamara/redaxo_yform_docs pull request #80
Opened 2017-10-19 07:14 UTC by tbaddade

2017-10-19 08:45 UTC, alexplusde commented
Das hatte ich so oder so ähnlich schon mal als Info bekommen von @dergel, beim eigenen Einbau hingegen wurde `$this` nicht gefunden. Hast du es selbst mal verwendet @tbaddade?

2017-10-19 08:52 UTC, tbaddade commented
> Hast du es selbst mal verwendet

@alexplusde Ja, hab es direkt aus einem Projekt herausgezogen.

2017-10-19 08:59 UTC, AWqxKAWERbXo requested changes
Kannst du auch die Beispiel-PHP-Schreibweise dazu notieren? Und ein Hinweis fehlt, dass das upload-Feld den Feldnamen "files" haben soll.

2017-10-19 09:21 UTC, tbaddade commented
> Und ein Hinweis fehlt, dass das upload-Feld den Feldnamen "files" haben soll.

Könnte sein, dass es deshalb bei dir nicht funktionierte. Der Feldname muss nicht `files` heißen. 
Siehe hier https://github.com/yakamara/redaxo_yform/blob/master/lib/yform/value/upload.php

2017-10-19 09:29 UTC, tbaddade commented
> Kannst du auch die Beispiel-PHP-Schreibweise dazu notieren?

@alexplusde Dazu fehlt mir grad eine Testumgebung auf einem Liveserver. Lokal gehen bei mir keine E-Mails raus. PHP kann man sich auch aus der Pipenotation ableiten, aber ohne zu testen nehme ich das ungern auf ;).

2017-10-19 21:07 UTC, alexplusde commented
> aber ohne zu testen nehme ich das ungern auf ;).

Da ist es bei mir nämlich auf jeden Fall gescheitert (egal, ob ich es direkt schreibe oder als Parameter übergebe) - ich wiederum hatte die PIPE-Schreibweise nicht genutzt.

Ich lass das hier mal für einen Moment offen und werde es nochmal selbst versuchen.

2018-01-12 13:01 UTC, alexplusde commented
Wir kommen da auf keinen grünen Zweig. @tbaddade oder @dergel könnt ihr euch das ausnahmsweise nochmal anschauen, ob und wie die PHP-Schreibweise richtig wäre? (die für $yform als Objekt, nicht über das Formbuilder-Modul)

2018-01-16 14:44 UTC, alexplusde commented
so, ich konnte mich jetzt mal in Ruhe damit beschäftigen. Es funktioniert, wie du es beschrieben hast, allerdings werde ich noch etwas mehr dazu erläutern und dann auch mergen.

Einzig den Parameter `database` verstehe ich nicht: Kommt da jetzt der Feldname oder der Tabellenname rein? Leider bietet auch der TableManager bei der Erstellung des Upload-Feldes nicht die nötige Hilfe, um die Parameter richtig zu setzen.

2018-01-17 07:28 UTC, alexplusde commented
```
$yform->setValueField('upload', array('upload','Dateianhang','100,10000','.pdf,.odt,.doc,.docx,.xls,.xlsx,.png,.jpg,.jpeg,.zip'));

$yform->setValueField('php', array('php_attach','Datei anhängen','<?php if (isset($this->params[\'value_pool\'][\'files\'])) { $this->params[\'value_pool\'][\'email_attachments\'] = $this->params[\'value_pool\'][\'files\']; } ?>'));
```

Memo für mich: Fehlermeldungen testen / einbauen.

2018-01-17 09:37 UTC, closed without merging